### ISSUE TITLE
Symlink refactoring

### ISSUE THREAD

**Issue by joliss** [broccolijs/broccoli#179]
Scratchpad to keep track of things. @rwjblue, please edit freely :)

Things to do:
## Part 1
- [x] ~~add `.brocignore` functionality to deal with Emacs lockfiles and such~~ (@joliss and @rwjblue decided to make this a plugin concern)
- [x] [`hashTree`](https://github.com/broccolijs/broccoli-kitchen-sink-helpers/blob/018583a1a56af810bf0e2a8bf6a3e4469daa3b7d/index.js#L10-L96) has murky edge cases, could likely just be rewritten (and extracted) - fixed in https://github.com/broccolijs/broccoli-kitchen-sink-helpers/pull/24 and we'll likely phase this function out in the future
- [x] though deprecated, perhaps we can simply change `copyRecursivelySync` and `copyPreserveSync` to use `stat` instead of `lstat` - https://github.com/broccolijs/broccoli-kitchen-sink-helpers/commit/02276ba63153d39db5c7473364dcd3727881d86b
- [x] [broccoli-concat](https://github.com/rlivsey/broccoli-concat/blob/master/index.js) (probably simply lstat to stat) - https://github.com/rlivsey/broccoli-concat/pull/15
- [x] broccoli-file-mover & remover - double-check symlink resolution; also, are we sure rimraf cannot delete source files now that path components can be symlinks?
- [x] ~~add symlink behavior to spec in README,~~ and make a document to describe this change and how it affects compatibility - [docs/symlink-change.md](https://github.com/broccolijs/broccoli/blob/master/docs/symlink-change.md) (work in progress)
## Part 2 - Symlink Consumption

Release updated package versions:
- [x] node-walk-sync
- [x] broccoli-kitchen-sink-helpers (https://github.com/broccolijs/broccoli-kitchen-sink-helpers/pull/24)
- [x] broccoli-file-mover & remover
- [x] broccoli-concat
- [x] broccoli-filter (it gets the new `hashTree` through a floating dependency)
- [x] broccoli
## Part 3 - Symlink Optimization

Release updated package versions:
- [x] broccoli-static-compiler (v0.2.0)
- [ ] broccoli-filter (https://github.com/broccolijs/broccoli-filter/pull/14 -- emit symlinks)
- [x] broccoli-merge-trees (v0.2.0)
## Part 4
- [ ] Windows performance: we can probably use symlinks when we have rights to, or junctions (not sure if that will lead to correct behavior), instead of [always copying](https://github.com/broccolijs/node-symlink-or-copy/blob/5e4ed362fb4206208583105d037adc4651cb5238/index.js#L14-L17)
- [ ] broccoli-caching-writer can use symlinking instead of hardlinking now
- [ ] allow for passing in existing `stats` and `lstats` objects into node-symlink-or-copy and node-copy-dereference
- [ ] there are more uses of deprecated helper functions like `copyRecursivelySync` [across GitHub](https://github.com/search?q=copyRecursivelySync&ref=cmdform&type=Code) - https://github.com/tildeio/htmlbars/pull/76

**Comment by stefanpenner** [comment]
this has landed, we can close.  If this hasn't fixed your issue, don't worry we have other things cooking to continue to help!
