### ISSUE TITLE
Port ember-cli/broccoli-builder to master

### ISSUE THREAD

**Issue by oligriffiths** [broccolijs/broccoli#360]
I am going to attempt to summarize the work that needs to be done to port the changes made to https://github.com/ember-cli/broccoli-builder into broccoli, so that the fork can be retired and `ember-cli` can use broccoli master

# Glossary:
* `master` refers to https://github.com/broccolijs/broccoli/tree/master
* `0-18-x` refers to https://github.com/ember-cli/broccoli-builder/tree/0-18-x
* Branch point: The commit `ab404ef725be5c265c901838be40d0358a867ec4` that ember-cli/broccoli-builder branched from broccoli master
* Branch point + tests: The commit just after branch point, `f5a1f3ddb1a01a4a9c312be12f1efed2b6d38611` that the test suite was converted from tap to mocha and exists in `master` but not `0-18-x`

# Diff:
I created a patch from `branch-point-with-tests` to `0-18-x` https://github.com/oligriffiths/broccoli-builder/pull/7 that shows the changes basically from the whole 0-18-x series so we can see what has actually changed (minus file deletions and the conversion of the test suite from tap to mocha).

# Todo:
* [x] On `0-18-x`, port test suite to mocha from `branch point + tests`, as this happened *just* after the branch point, so to make comparisons easier I have ported the test suite to use mocha
* [x] On `master`, add the ability to overwrite a `dist` directory without having to remove the directory first https://github.com/broccolijs/broccoli/pull/354
* [x] On `master`, port the protection of the `dist` directory from `-0-18-x` if it's a direct parent of the project https://github.com/broccolijs/broccoli/pull/358
* [x] On `0-18x` deprecate `api_compat.js`. This was to support the old read API, and is no longer supported in Broccoli and hasn’t been used in ember for some time. Start with a console warning, then remove.  https://github.com/oligriffiths/broccoli-builder/blob/diff/lib/api_compat.js https://github.com/ember-cli/broccoli-builder/pull/26
* [ ] On `0-18x` kill `api_compat.js`.
* [x] On `master`, port `heimdall` stats collection from `0-18-x`  Investigate the event api in Broccoli for this instead of hand jamming: https://github.com/broccolijs/broccoli/pull/362
* [x] On `master`, port `cancellation` from `0-18-x` https://github.com/broccolijs/broccoli/pull/350
* [ ] On `master` port `broccoli-build-error` from `0-18-x` https://github.com/oligriffiths/broccoli-builder/blob/diff/lib/broccoli-build-error.js this is a nicer error output that only shows the stack trace for where the error happened within a Broccoli plugin
* [x] On `master` validate the ability to have the `tmp` directory in the project root (per ember-cli) for compat with addons that have used this hack
https://github.com/ember-cli/ember-cli/pull/7798

# Bonus points
* [ ] Mid-build change events should cancel the current build and queue up behind the existing cancel before kicking off another build. This allows for if a watched file changing mid build, to cancel the current build and kick off a new one. This is out of scope for upstreaming to master. https://github.com/broccolijs/broccoli/pull/350

**Comment by oligriffiths** [comment]
Ok, here's the state of play:

Heimdall support: https://github.com/broccolijs/broccoli/pull/362
Broccoli-1 support in ember-cli https://github.com/ember-cli/ember-cli/pull/7798 - this includes `tmp` support in project root

**Comment by stefanpenner** [comment]
@oligriffiths what about the watcher-middleware? I think unifying them (if they are not already) is important. Specifically: https://github.com/ember-cli/broccoli-middleware/blob/master/lib/watcher-middleware.js#L30

Which enables: https://github.com/ember-cli/rfcs/pull/80

**Comment by oligriffiths** [comment]
@stefanpenner I think we should do that as a separate step as it’s not directly part of Broccoli-builder and the intention here is to remove the builder.

**Comment by oligriffiths** [comment]
To clarify, as part of the existing builder work no, as part of the quest, yes

**Comment by stefanpenner** [comment]
@oligriffiths can you confirm but I believe this has landed right?

**Comment by oligriffiths** [comment]
Yup
